'''
Created on 28 de jun. de 2016

@author: Rottweilas
'''

#CATALOGO PARA PROFESOR
PROFESOR_TIPO_PROFESOR = 10
PROFESOR_GRADO_ACADEMICO = 9
PROFESOR_ESTADO_PROFESOR = 3

#CATALOGO PARA TUTORE
TUTOR_ESTADO_TUTOR = 4
TUTOR_EST_ACTIVO = 1
TUTOR_EST_NO_ACTIVO = 2

#CATALOGO PARA ALUMNO
ALUMNO_ESTADO_ALUMNO = 2
ALUMNO_EST_MATRICULADO = 1
ALUMNO_EST_NO_MATRICULADO = 2
ALUMNO_ESTA_EXPULSADO = 3

#CATALOGO PARA MATRICULA
MATRICULA_ESTADO_MATRICULA =1
MATRICULA_EST_ACTUALIZADA = 1
MATRICULA_EST_NO_ACTUALIZADA = 2

#CATALOGO PARA CURSO
CURSO_TIPO_CURSO = 6 
CURSO_ESTADO_CURSO = 11
CURSO_EST_ACTIVO = 1
CURSO_EST_NO_ACTIVO = 2

#CATALOGO CURSO GRADO SECCION
CURGRADSEC_TIPO_ASIGNADO = 13
CURGRADSEC_ASIGNADO = 1
CURGRADSEC_NO_ASIGNADO = 2

#CATALOGO PARA SECCION
SECCION_TIPO_SECCION = 7
